---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alberth270/SpringClound
          searchPaths: ConfigData
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001
